import { afterEach, describe, expect, it } from "vitest";
import { mkdtempSync, rmSync } from "node:fs"; import { join } from "node:path"; import { tmpdir } from "node:os";
import { DaniControlPlane, digestJson } from "./dani-control-plane.ts";
const roots:string[]=[]; afterEach(()=>roots.splice(0).forEach(r=>rmSync(r,{recursive:true,force:true})));
const plane=()=>{const r=mkdtempSync(join(tmpdir(),"dani-cp-"));roots.push(r);return new DaniControlPlane(join(r,"control.db"));};
describe("DaniControlPlane",()=>{
 it("deduplicates external events and idempotent effects",()=>{const p=plane();const e={ownerId:"u",source:"webhook" as const,sourceId:"evt-1",type:"changed",occurredAt:new Date().toISOString(),payload:{x:1}};expect(p.ingestEvent(e).duplicate).toBe(false);expect(p.ingestEvent(e).duplicate).toBe(true);const j=p.createJob({ownerId:"u",objective:"ship",successCriteria:["verified"]});expect(p.planEffect({jobId:String(j.id),tool:"github.write",target:"repo",arguments:{a:1},idempotencyKey:"k"}).duplicate).toBe(false);expect(p.planEffect({jobId:String(j.id),tool:"github.write",target:"repo",arguments:{a:1},idempotencyKey:"k"}).duplicate).toBe(true);p.close();});
 it("leases one job and supports pause resume cancel",()=>{const p=plane();const j=p.createJob({ownerId:"u",objective:"work",successCriteria:["done"]});expect(p.claimNext("u","w")?.id).toBe(j.id);expect(p.claimNext("u","w2")).toBeNull();p.pause(String(j.id),"user");p.resume(String(j.id));p.cancel(String(j.id),"stop");expect(p.job(String(j.id)).state).toBe("cancelled");p.close();});
 it("fails closed on expired approval and records evidence",()=>{const p=plane();const j=p.createJob({ownerId:"u",objective:"send",successCriteria:["receipt"]});const e=p.planEffect({jobId:String(j.id),tool:"mail.send",target:"a@b",arguments:{body:"x"},idempotencyKey:"1"});const a=p.requestApproval(String(j.id),String(e.id),1);expect(p.decideApproval(a.id,"approved","9999-01-01T00:00:00Z")).toBe("denied");p.addEvidence({jobId:String(j.id),effectId:String(e.id),kind:"external_read",source:"mail",observedAt:new Date().toISOString(),observation:{sent:false},digest:digestJson({sent:false})});expect(p.auditTrail(String(j.id)).some(x=>x.kind==="approval.denied")).toBe(true);p.close();});
});
