import { afterEach, describe, expect, it, vi } from "vitest";
import { closeSync, mkdtempSync, openSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { DatabaseSync } from "node:sqlite";
import { DaniControlPlane, digestJson } from "./dani-control-plane.ts";
import { DaniToolExecutor, DaniToolRegistry, toolEvidence } from "./dani-tools.ts";
const roots:string[]=[];
afterEach(()=>roots.splice(0).forEach(root=>rmSync(root,{recursive:true,force:true})));
const make=()=>{const root=mkdtempSync(join(tmpdir(),"dani-recovery-"));roots.push(root);return{root,path:join(root,"control.db"),plane:new DaniControlPlane(join(root,"control.db"))}};
const job=(plane:DaniControlPlane)=>plane.createJob({ownerId:"owner",objective:"download",successCriteria:["verified file"]});

describe("runtime effects and recovery",()=>{
 it("uses the full canonical effect fingerprint and rejects idempotency collisions",()=>{const{plane}=make(),j=job(plane);const base={jobId:j.id,tool:"browser.download",target:"fixture",arguments:{b:2,a:1},idempotencyKey:"download-1",preconditions:{path:"Downloads"},approvalScope:{owner:"owner"},resourceIdentity:"desktop:1"};const first=plane.planEffect(base);expect(first.duplicate).toBe(false);expect(plane.planEffect({...base,arguments:{a:1,b:2}}).duplicate).toBe(true);expect(()=>plane.planEffect({...base,preconditions:{path:"Desktop"}})).toThrow(/different effect fingerprint/);plane.close()});
 it("binds approval to the full fingerprint",()=>{const{plane}=make(),j=job(plane),effect=plane.planEffect({jobId:j.id,tool:"browser.download",target:"fixture",arguments:{name:"a"},idempotencyKey:"k",preconditions:{etag:"v1"},approvalScope:{write:true}}),approval=plane.requestApproval(j.id,effect.id);plane.db.prepare("UPDATE dani_effects SET fingerprint=? WHERE id=?").run("tampered",effect.id);expect(plane.decideApproval(approval.id,"approved")).toBe("denied");plane.close()});
 it("migrates a version-one database without losing effects",()=>{const root=mkdtempSync(join(tmpdir(),"dani-migrate-"));roots.push(root);const path=join(root,"old.db"),db=new DatabaseSync(path);db.exec("CREATE TABLE dani_jobs(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,objective TEXT NOT NULL,criteria TEXT NOT NULL,state TEXT NOT NULL,priority INTEGER NOT NULL,attempt INTEGER NOT NULL,max_attempts INTEGER NOT NULL,budget TEXT NOT NULL,usage TEXT NOT NULL,quiet_hours TEXT,lease_owner TEXT,lease_expires_at TEXT,pause_reason TEXT,cancel_reason TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE dani_effects(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES dani_jobs(id),tool TEXT NOT NULL,target TEXT NOT NULL,arguments TEXT NOT NULL,arguments_digest TEXT NOT NULL,idempotency_key TEXT NOT NULL,state TEXT NOT NULL,authorization_id TEXT,external_reference TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(job_id,idempotency_key));");db.prepare("INSERT INTO dani_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("j","owner","o","[]","ready",0,0,3,"{}","{}",null,null,null,null,null,"t","t");db.prepare("INSERT INTO dani_effects VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run("e","j","x","y","{}",digestJson({}),"k","planned",null,null,null,"t","t");db.close();const plane=new DaniControlPlane(path);expect(plane.effect("e").preconditions).toEqual({});expect((plane.db.prepare("PRAGMA user_version").get() as {user_version:number}).user_version).toBe(2);plane.close()});
 it("turns an unacknowledged dispatch into canonical unknown after restart",()=>{const{path,plane}=make(),j=job(plane),effect=plane.planEffect({jobId:j.id,tool:"browser.download",target:"fixture",arguments:{},idempotencyKey:"k"});plane.effectState(effect.id,"authorized");const attempt=plane.beginAttempt(effect.id,"worker");plane.effectState(effect.id,"dispatched");expect(attempt.attemptNo).toBe(1);plane.close();const recovered=new DaniControlPlane(path);expect(recovered.recoverUnknownEffects()).toBe(1);expect(recovered.effect(effect.id).state).toBe("unknown");expect(recovered.job(j.id).state).toBe("unknown");recovered.close()});
 it("fences a single physical desktop lease and invalidates stale holders",()=>{const{plane}=make(),a=job(plane),b=job(plane),first=plane.acquireResourceLease("desktop:physical","owner",a.id,"w1",60_000);expect(()=>plane.acquireResourceLease("desktop:physical","owner",b.id,"w2",60_000)).toThrow(/held/);plane.db.prepare("UPDATE dani_resource_leases SET expires_at='2000-01-01T00:00:00.000Z' WHERE resource_id='desktop:physical'").run();const second=plane.acquireResourceLease("desktop:physical","owner",b.id,"w2",60_000);expect(second.fence).toBe(first.fence+1);expect(()=>plane.assertResourceLease("desktop:physical","w1",first.fence)).toThrow(/stale/);plane.assertResourceLease("desktop:physical","w2",second.fence);plane.close()});
 it("keeps attempt rows immutable",()=>{const{plane}=make(),j=job(plane),effect=plane.planEffect({jobId:j.id,tool:"x",target:"y",arguments:{},idempotencyKey:"k"});const attempt=plane.beginAttempt(effect.id,"worker");plane.finishAttempt(attempt.id,"failed",{error:"no"});expect(()=>plane.finishAttempt(attempt.id,"confirmed")).toThrow(/immutable/);expect(plane.attempts(effect.id)).toHaveLength(1);plane.close()});
 it("reconciles unknown duplicates before retry and never redispatches them",async()=>{const{plane}=make(),j=job(plane),registry=new DaniToolRegistry(),execute=vi.fn(),reconcile=vi.fn(async(_input:any,context:any)=>({confirmed:true,externalReference:"file",evidence:[toolEvidence(context.jobId,context.effectId,"filesystem",{exists:true},true,"fs.stat")]}));registry.register({name:"browser.download",description:"download",risk:"read",inputSchema:{},outputSchema:{},idempotency:"reconcile",timeoutMs:100,execute,reconcile});const effect=plane.planEffect({jobId:j.id,tool:"browser.download",target:"fixture",arguments:{},idempotencyKey:"k"});plane.effectState(effect.id,"unknown");const result=await new DaniToolExecutor(plane,registry).execute(j.id,"owner","browser.download","fixture",{},"k",new AbortController().signal);expect(result.status).toBe("confirmed");expect(reconcile).toHaveBeenCalledOnce();expect(execute).not.toHaveBeenCalled();plane.close()});
 it("requires fresh verified evidence rather than evidence presence",async()=>{const{plane}=make(),j=job(plane),registry=new DaniToolRegistry();registry.register({name:"read",description:"read",risk:"read",inputSchema:{},outputSchema:{},idempotency:"read-only",timeoutMs:100,execute:async(_input:any,context:any)=>({output:"seen",evidence:[{...toolEvidence(context.jobId,context.effectId,"cache",{seen:true},false),observedAt:"2000-01-01T00:00:00.000Z"}]})});const result=await new DaniToolExecutor(plane,registry).execute(j.id,"owner","read","resource",{},"k",new AbortController().signal);expect(result.status).toBe("unknown");expect(plane.effect(result.effectId).state).toBe("unknown");plane.close()});
 it("prevents dispatch after cancellation",async()=>{const{plane}=make(),j=job(plane),registry=new DaniToolRegistry(),execute=vi.fn();registry.register({name:"read",description:"read",risk:"read",inputSchema:{},outputSchema:{},idempotency:"read-only",timeoutMs:100,execute});plane.cancel(j.id,"stop");await expect(new DaniToolExecutor(plane,registry).execute(j.id,"owner","read","x",{},"k",new AbortController().signal)).rejects.toThrow(/cancelled/);expect(execute).not.toHaveBeenCalled();plane.close()});
 it("records one canonical attempt under concurrent duplicate execution",async()=>{const{plane}=make(),j=job(plane),registry=new DaniToolRegistry(),release:{resolve?:(value:unknown)=>void}={},gate=new Promise(resolve=>{release.resolve=resolve}),execute=vi.fn(async(_input:any,context:any)=>{await gate;return{output:"ok",evidence:[toolEvidence(context.jobId,context.effectId,"test",{ok:true})]}});registry.register({name:"read",description:"read",risk:"read",inputSchema:{},outputSchema:{},idempotency:"read-only",timeoutMs:100,execute});const runner=new DaniToolExecutor(plane,registry),signal=new AbortController().signal,first=runner.execute(j.id,"owner","read","x",{},"k",signal);await vi.waitFor(()=>expect(execute).toHaveBeenCalledOnce());const second=await runner.execute(j.id,"owner","read","x",{},"k",signal);expect(second.status).toBe("unknown");release.resolve?.(null);expect((await first).status).toBe("confirmed");expect(execute).toHaveBeenCalledOnce();plane.close()});
 it("can verify a real filesystem observation",()=>{const{root,plane}=make(),j=job(plane),effect=plane.planEffect({jobId:j.id,tool:"filesystem.write",target:"Downloads/a.txt",arguments:{},idempotencyKey:"k"}),path=join(root,"a.txt");closeSync(openSync(path,"w"));const observedAt=new Date().toISOString();plane.addEvidence({jobId:j.id,effectId:effect.id,kind:"external_read",source:"fs.stat",observedAt,observation:{path,exists:true},digest:digestJson({path,exists:true}),verified:true,verifier:"fs.stat"});expect(plane.hasFreshVerifiedEvidence(effect.id,observedAt)).toBe(true);plane.close()});
});
