import { randomUUID } from "node:crypto";
import type { DaniToolDefinition } from "../shared/dani-runtime.ts";
import { DaniControlPlane, digestJson } from "./dani-control-plane.ts";
export class DaniToolRegistry { private tools=new Map<string,DaniToolDefinition<any,any>>();register<I,O>(tool:DaniToolDefinition<I,O>){if(this.tools.has(tool.name))throw new Error(`duplicate tool ${tool.name}`);this.tools.set(tool.name,tool)}get(name:string){const tool=this.tools.get(name);if(!tool)throw new Error(`unknown tool ${name}`);return tool}}
export class DaniToolExecutor {constructor(private plane:DaniControlPlane,private registry:DaniToolRegistry){}
 async execute(jobId:string,ownerId:string,toolName:string,target:string,args:unknown,idempotencyKey:string,signal:AbortSignal,options:{preconditions?:unknown;approvalScope?:unknown;resourceIdentity?:string;workerId?:string}={}){const tool=this.registry.get(toolName),workerId=options.workerId??"runtime";this.plane.assertDispatchable(jobId);const effect=this.plane.planEffect({jobId,tool:toolName,target,arguments:args,idempotencyKey,preconditions:options.preconditions,approvalScope:options.approvalScope,resourceIdentity:options.resourceIdentity});
  if(effect.duplicate){if(effect.state==="confirmed")return{status:"confirmed" as const,effectId:effect.id};if(["dispatched","unknown"].includes(effect.state)){if(!tool.reconcile)return{status:"unknown" as const,effectId:effect.id};const reconciled=await tool.reconcile(args,{jobId,effectId:effect.id,signal});for(const evidence of reconciled.evidence)this.plane.addEvidence(evidence);if(reconciled.confirmed&&reconciled.evidence.some(item=>item.verified)){this.plane.effectState(effect.id,"confirmed",{externalReference:reconciled.externalReference});return{status:"confirmed" as const,effectId:effect.id}}return{status:"unknown" as const,effectId:effect.id};}if(effect.state!=="authorized")return{status:"approval_required" as const,effectId:effect.id};
  }else{const grant=this.plane.activeGrant(ownerId,toolName,target);if(tool.risk!=="read"&&!grant){this.plane.requestApproval(jobId,effect.id);return{status:"approval_required" as const,effectId:effect.id}}this.plane.effectState(effect.id,"authorized");}
  this.plane.assertDispatchable(jobId);if(signal.aborted)throw signal.reason??new Error("cancelled");const attempt=this.plane.beginAttempt(effect.id,workerId);this.plane.effectState(effect.id,"dispatched");const dispatchedAt=new Date().toISOString();try{const result=await tool.execute(args,{jobId,effectId:effect.id,signal});for(const evidence of result.evidence)this.plane.addEvidence(evidence);if(!result.evidence.some(item=>item.verified)||!this.plane.hasFreshVerifiedEvidence(effect.id,dispatchedAt))throw new Error("tool returned no fresh verified evidence");this.plane.finishAttempt(attempt.id,"confirmed",{externalReference:result.externalReference});this.plane.effectState(effect.id,"confirmed",{externalReference:result.externalReference});return{status:"confirmed" as const,effectId:effect.id,output:result.output};}catch(error){const message=error instanceof Error?error.message:String(error);if(tool.reconcile){const result=await tool.reconcile(args,{jobId,effectId:effect.id,signal});for(const evidence of result.evidence)this.plane.addEvidence(evidence);if(result.confirmed&&result.evidence.some(item=>item.verified)){this.plane.finishAttempt(attempt.id,"confirmed",{externalReference:result.externalReference});this.plane.effectState(effect.id,"confirmed",{externalReference:result.externalReference});return{status:"confirmed" as const,effectId:effect.id};}}this.plane.finishAttempt(attempt.id,"unknown",{error:message});this.plane.effectState(effect.id,"unknown",{error:message});return{status:"unknown" as const,effectId:effect.id};}}
}
export const toolEvidence=(jobId:string,effectId:string,source:string,observation:unknown,verified=true,verifier="tool")=>({jobId,effectId,kind:"tool_result" as const,source,observedAt:new Date().toISOString(),observation,digest:digestJson(observation),verified,verifier});
export const newIdempotencyKey=(jobId:string,tool:string,target:string,args:unknown)=>`${jobId}:${tool}:${target}:${digestJson(args)}`;
export const newGrantId=()=>randomUUID();
