import { randomUUID } from "node:crypto";
import type { DaniToolDefinition } from "../shared/dani-runtime.ts";
import { DaniControlPlane, digestJson } from "./dani-control-plane.ts";
export class DaniToolRegistry { private tools=new Map<string,DaniToolDefinition<any,any>>();register<I,O>(tool:DaniToolDefinition<I,O>){if(this.tools.has(tool.name))throw new Error(`duplicate tool ${tool.name}`);this.tools.set(tool.name,tool)}get(name:string){const t=this.tools.get(name);if(!t)throw new Error(`unknown tool ${name}`);return t}}
export class DaniToolExecutor {constructor(private plane:DaniControlPlane,private registry:DaniToolRegistry){}
 async execute(jobId:string,ownerId:string,toolName:string,target:string,args:unknown,idempotencyKey:string,signal:AbortSignal){const tool=this.registry.get(toolName);const effect=this.plane.planEffect({jobId,tool:toolName,target,arguments:args,idempotencyKey});if(!effect.duplicate){const grant=this.plane.activeGrant(ownerId,toolName,target);if(tool.risk!=="read"&&!grant){this.plane.requestApproval(jobId,effect.id);return{status:"approval_required" as const,effectId:effect.id}}this.plane.effectState(effect.id,"authorized")}else{if(effect.state==="confirmed")return{status:"confirmed" as const,effectId:effect.id};if(effect.state!=="authorized"&&effect.state!=="dispatched"&&effect.state!=="uncertain")return{status:"approval_required" as const,effectId:effect.id}}this.plane.effectState(effect.id,"dispatched");try{const result=await tool.execute(args,{jobId,effectId:effect.id,signal});for(const evidence of result.evidence)this.plane.addEvidence(evidence);if(!result.evidence.length)throw new Error("tool returned no verification evidence");this.plane.effectState(effect.id,"confirmed",{externalReference:result.externalReference});return{status:"confirmed" as const,effectId:effect.id,output:result.output}}catch(error){if(tool.reconcile){const r=await tool.reconcile(args,{jobId,effectId:effect.id,signal});for(const e of r.evidence)this.plane.addEvidence(e);if(r.confirmed){this.plane.effectState(effect.id,"confirmed",{externalReference:r.externalReference});return{status:"confirmed" as const,effectId:effect.id}}}this.plane.effectState(effect.id,"uncertain",{error:error instanceof Error?error.message:String(error)});return{status:"uncertain" as const,effectId:effect.id}}}
}
export const toolEvidence=(jobId:string,effectId:string,source:string,observation:unknown)=>({jobId,effectId,kind:"tool_result" as const,source,observedAt:new Date().toISOString(),observation,digest:digestJson(observation)});
export const newIdempotencyKey=(jobId:string,tool:string,target:string,args:unknown)=>`${jobId}:${tool}:${target}:${digestJson(args)}`;
export const newGrantId=()=>randomUUID();
