import { createHash, randomUUID } from "node:crypto";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import type { DaniEffectPlan, DaniEventInput, DaniEvidenceInput, DaniGrant, DaniJobInput, DaniJobState } from "../shared/dani-runtime.ts";

const json = (value: unknown) => JSON.stringify(value);
const parse = <T>(value: unknown): T => JSON.parse(String(value)) as T;
const now = () => new Date().toISOString();
type SqlRow = Record<string, unknown>;
export interface StoredJob extends SqlRow { id: string; owner_id: string; state: DaniJobState; criteria: string[]; budget: unknown; usage: unknown; quiet_hours: unknown }
export interface StoredEffect extends SqlRow { id: string; job_id: string; arguments: unknown; duplicate: boolean }
export const digestJson = (value: unknown) => createHash("sha256").update(json(value)).digest("hex");

export class DaniControlPlane {
  readonly db: DatabaseSync;
  constructor(path: string) { mkdirSync(dirname(path), { recursive: true }); this.db = new DatabaseSync(path); this.migrate(); }
  private migrate() { this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
    CREATE TABLE IF NOT EXISTS dani_events(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,source TEXT NOT NULL,source_id TEXT NOT NULL,type TEXT NOT NULL,occurred_at TEXT NOT NULL,payload TEXT NOT NULL,digest TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(owner_id,source,source_id));
    CREATE TABLE IF NOT EXISTS dani_jobs(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,objective TEXT NOT NULL,criteria TEXT NOT NULL,state TEXT NOT NULL,priority INTEGER NOT NULL,attempt INTEGER NOT NULL,max_attempts INTEGER NOT NULL,budget TEXT NOT NULL,usage TEXT NOT NULL,quiet_hours TEXT,lease_owner TEXT,lease_expires_at TEXT,pause_reason TEXT,cancel_reason TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS dani_effects(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES dani_jobs(id),tool TEXT NOT NULL,target TEXT NOT NULL,arguments TEXT NOT NULL,arguments_digest TEXT NOT NULL,idempotency_key TEXT NOT NULL,state TEXT NOT NULL,authorization_id TEXT,external_reference TEXT,error TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(job_id,idempotency_key));
    CREATE TABLE IF NOT EXISTS dani_evidence(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES dani_jobs(id),effect_id TEXT REFERENCES dani_effects(id),kind TEXT NOT NULL,source TEXT NOT NULL,observed_at TEXT NOT NULL,observation TEXT NOT NULL,digest TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(job_id,digest));
    CREATE TABLE IF NOT EXISTS dani_grants(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,tool_pattern TEXT NOT NULL,target_pattern TEXT NOT NULL,constraints TEXT NOT NULL,expires_at TEXT,revoked_at TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS dani_approvals(id TEXT PRIMARY KEY,job_id TEXT NOT NULL REFERENCES dani_jobs(id),effect_id TEXT NOT NULL REFERENCES dani_effects(id),action_digest TEXT NOT NULL,state TEXT NOT NULL,expires_at TEXT NOT NULL,decided_at TEXT,created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS dani_audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,owner_id TEXT NOT NULL,job_id TEXT,kind TEXT NOT NULL,detail TEXT NOT NULL,at TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS dani_jobs_active ON dani_jobs(owner_id,state,priority DESC,created_at); CREATE INDEX IF NOT EXISTS dani_effects_job ON dani_effects(job_id,state);`); }
  close() { this.db.close(); }
  private audit(ownerId: string, jobId: string | null, kind: string, detail: unknown) { this.db.prepare("INSERT INTO dani_audit(owner_id,job_id,kind,detail,at) VALUES(?,?,?,?,?)").run(ownerId, jobId, kind, json(detail), now()); }
  ingestEvent(input: DaniEventInput) { const id=randomUUID(), at=now(), digest=digestJson(input.payload); const result=this.db.prepare("INSERT OR IGNORE INTO dani_events VALUES(?,?,?,?,?,?,?,?,?)").run(id,input.ownerId,input.source,input.sourceId,input.type,input.occurredAt,json(input.payload),digest,at); const row=this.db.prepare("SELECT * FROM dani_events WHERE owner_id=? AND source=? AND source_id=?").get(input.ownerId,input.source,input.sourceId) as Record<string,unknown>; if(result.changes) this.audit(input.ownerId,null,"event.ingested",{id:row.id,source:input.source,type:input.type}); return {id:String(row.id),duplicate:result.changes===0,digest:String(row.digest)}; }
  createJob(input: DaniJobInput) { const id=randomUUID(), at=now(); this.db.prepare("INSERT INTO dani_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,input.ownerId,input.objective,json(input.successCriteria),"ready",input.priority??0,0,input.maxAttempts??3,json(input.budget??{}),json({turns:0,toolCalls:0,costUsd:0}),input.quietHours?json(input.quietHours):null,null,null,null,null,at,at); this.audit(input.ownerId,id,"job.created",input); return this.job(id); }
  job(id:string): StoredJob { const row=this.db.prepare("SELECT * FROM dani_jobs WHERE id=?").get(id) as SqlRow|undefined; if(!row) throw new Error("job not found"); return {...row,id:String(row.id),owner_id:String(row.owner_id),state:String(row.state) as DaniJobState,criteria:parse<string[]>(row.criteria),budget:parse(row.budget),usage:parse(row.usage),quiet_hours:row.quiet_hours?parse(row.quiet_hours):null}; }
  transition(id:string, from:DaniJobState[], to:DaniJobState, detail:Record<string,unknown>={}) { const job=this.job(id); if(!from.includes(job.state as DaniJobState)) throw new Error(`invalid job transition ${job.state} -> ${to}`); this.db.prepare("UPDATE dani_jobs SET state=?,updated_at=? WHERE id=?").run(to,now(),id); this.audit(String(job.owner_id),id,`job.${to}`,detail); return this.job(id); }
  claimNext(ownerId:string,workerId:string,leaseMs=30_000) { const at=now(), expires=new Date(Date.now()+leaseMs).toISOString(); this.db.exec("BEGIN IMMEDIATE"); try { const row=this.db.prepare("SELECT id FROM dani_jobs WHERE owner_id=? AND state='ready' AND (lease_expires_at IS NULL OR lease_expires_at<?) ORDER BY priority DESC,created_at LIMIT 1").get(ownerId,at) as {id:string}|undefined; if(!row){this.db.exec("COMMIT");return null;} this.db.prepare("UPDATE dani_jobs SET state='running',lease_owner=?,lease_expires_at=?,attempt=attempt+1,updated_at=? WHERE id=?").run(workerId,expires,at,row.id); this.db.exec("COMMIT"); const job=this.job(row.id); this.audit(ownerId,row.id,"job.claimed",{workerId,expires}); return job; } catch(e){this.db.exec("ROLLBACK");throw e;} }
  pause(id:string,reason:string){const j=this.job(id);this.db.prepare("UPDATE dani_jobs SET state='paused',pause_reason=?,lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=?").run(reason,now(),id);this.audit(String(j.owner_id),id,"job.paused",{reason});}
  resume(id:string){const j=this.job(id);if(j.state!=="paused")throw new Error("job is not paused");this.db.prepare("UPDATE dani_jobs SET state='ready',pause_reason=NULL,updated_at=? WHERE id=?").run(now(),id);this.audit(String(j.owner_id),id,"job.resumed",{});}
  cancel(id:string,reason:string){const j=this.job(id);if(["succeeded","cancelled"].includes(String(j.state)))return;this.db.prepare("UPDATE dani_jobs SET state='cancelled',cancel_reason=?,lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE id=?").run(reason,now(),id);this.audit(String(j.owner_id),id,"job.cancelled",{reason});}
  planEffect(plan:DaniEffectPlan){const job=this.job(plan.jobId),id=randomUUID(),at=now(),argsDigest=digestJson(plan.arguments);this.db.prepare("INSERT OR IGNORE INTO dani_effects VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,plan.jobId,plan.tool,plan.target,json(plan.arguments),argsDigest,plan.idempotencyKey,"planned",plan.authorizationId??null,null,null,at,at);const row=this.db.prepare("SELECT * FROM dani_effects WHERE job_id=? AND idempotency_key=?").get(plan.jobId,plan.idempotencyKey) as Record<string,unknown>;this.audit(String(job.owner_id),plan.jobId,"effect.planned",{effectId:row.id,tool:plan.tool,target:plan.target,duplicate:row.id!==id});return {...row,id:String(row.id),job_id:String(row.job_id),arguments:parse(row.arguments),duplicate:row.id!==id} as StoredEffect;}
  effectState(id:string,state:string,fields:{externalReference?:string,error?:string}={}){const row=this.db.prepare("SELECT e.*,j.owner_id FROM dani_effects e JOIN dani_jobs j ON j.id=e.job_id WHERE e.id=?").get(id) as Record<string,unknown>|undefined;if(!row)throw new Error("effect not found");this.db.prepare("UPDATE dani_effects SET state=?,external_reference=COALESCE(?,external_reference),error=COALESCE(?,error),updated_at=? WHERE id=?").run(state,fields.externalReference??null,fields.error??null,now(),id);this.audit(String(row.owner_id),String(row.job_id),`effect.${state}`,{effectId:id,...fields});}
  addEvidence(input:DaniEvidenceInput){const id=randomUUID(),at=now();this.db.prepare("INSERT OR IGNORE INTO dani_evidence VALUES(?,?,?,?,?,?,?,?,?)").run(id,input.jobId,input.effectId??null,input.kind,input.source,input.observedAt,json(input.observation),input.digest,at);return id;}
  addGrant(grant:DaniGrant){this.db.prepare("INSERT INTO dani_grants VALUES(?,?,?,?,?,?,?,?)").run(grant.id,grant.ownerId,grant.toolPattern,grant.targetPattern,json(grant.constraints),grant.expiresAt,grant.revokedAt,now());return grant;}
  activeGrant(ownerId:string,tool:string,target:string,at=now()){const rows=this.db.prepare("SELECT * FROM dani_grants WHERE owner_id=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?)").all(ownerId,at) as Record<string,unknown>[];const match=(p:string,v:string)=>p==="*"||p===v||(p.endsWith("*")&&v.startsWith(p.slice(0,-1)));const row=rows.find(r=>match(String(r.tool_pattern),tool)&&match(String(r.target_pattern),target));return row?{...row,constraints:parse(row.constraints)}:null;}
  requestApproval(jobId:string,effectId:string,ttlMs=300_000){const job=this.job(jobId),effect=this.db.prepare("SELECT * FROM dani_effects WHERE id=? AND job_id=?").get(effectId,jobId) as Record<string,unknown>|undefined;if(!effect)throw new Error("effect not found");const id=randomUUID(),at=now(),expires=new Date(Date.now()+ttlMs).toISOString();this.db.prepare("INSERT INTO dani_approvals VALUES(?,?,?,?,?,?,?,?)").run(id,jobId,effectId,String(effect.arguments_digest),"pending",expires,null,at);this.db.prepare("UPDATE dani_jobs SET state='waiting_approval',updated_at=? WHERE id=?").run(at,jobId);this.audit(String(job.owner_id),jobId,"approval.requested",{id,effectId,expires});return{id,expiresAt:expires};}
  decideApproval(id:string,decision:"approved"|"denied",at=now()){const row=this.db.prepare("SELECT a.*,j.owner_id FROM dani_approvals a JOIN dani_jobs j ON j.id=a.job_id WHERE a.id=?").get(id) as Record<string,unknown>|undefined;if(!row)throw new Error("approval not found");if(row.state!=="pending")throw new Error("approval already decided");if(String(row.expires_at)<=at)decision="denied";this.db.prepare("UPDATE dani_approvals SET state=?,decided_at=? WHERE id=?").run(decision,at,id);this.db.prepare("UPDATE dani_jobs SET state=?,updated_at=? WHERE id=?").run(decision==="approved"?"ready":"failed",at,String(row.job_id));this.audit(String(row.owner_id),String(row.job_id),`approval.${decision}`,{id});return decision;}
  auditTrail(jobId:string){return this.db.prepare("SELECT seq,kind,detail,at FROM dani_audit WHERE job_id=? ORDER BY seq").all(jobId).map((r:any)=>({...r,detail:parse(r.detail)}));}
}
