import{createHash}from"node:crypto";
export interface TriggerRule{id:string;eventType:string;predicate?:Record<string,string|number|boolean>;dedupeWindowMs:number;enabled:boolean}
export interface ScheduleRule{id:string;timezone:string;nextRunAt:string;intervalMs?:number;enabled:boolean}
export interface ExecutionBudget{turns:number;toolCalls:number;costUsd:number;deadlineAt?:string}
export const stableTriggerKey=(ruleId:string,event:{sourceId:string;type:string;payload:unknown})=>createHash("sha256").update(JSON.stringify([ruleId,event.sourceId,event.type,event.payload])).digest("hex");
export function triggerMatches(rule:TriggerRule,event:{type:string;payload:unknown}){if(!rule.enabled||rule.eventType!==event.type)return false;if(!rule.predicate)return true;if(!event.payload||typeof event.payload!=="object")return false;return Object.entries(rule.predicate).every(([k,v])=>(event.payload as Record<string,unknown>)[k]===v)}
export function withinQuietHours(at:Date,quiet:{timezone:string;start:string;end:string}){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:quiet.timezone,hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(at);const mins=Number(parts.find(x=>x.type==="hour")?.value)*60+Number(parts.find(x=>x.type==="minute")?.value);const parse=(s:string)=>{const[h,m]=s.split(":").map(Number);return h!*60+m!},start=parse(quiet.start),end=parse(quiet.end);return start<=end?mins>=start&&mins<end:mins>=start||mins<end}
export function budgetAllows(budget:ExecutionBudget,usage:{turns:number;toolCalls:number;costUsd:number},now=new Date()){if(budget.deadlineAt&&now>=new Date(budget.deadlineAt))return{ok:false as const,reason:"deadline"};if(usage.turns>=budget.turns)return{ok:false as const,reason:"turns"};if(usage.toolCalls>=budget.toolCalls)return{ok:false as const,reason:"tool_calls"};if(usage.costUsd>=budget.costUsd)return{ok:false as const,reason:"cost"};return{ok:true as const}}
export function retryDelay(attempt:number,baseMs=1000,maxMs=60_000){return Math.min(maxMs,baseMs*2**Math.max(0,attempt-1))}
