import {afterEach,describe,expect,it} from "vitest";import{mkdtempSync,rmSync}from"node:fs";import{join}from"node:path";import{tmpdir}from"node:os";import type{ProviderInstance,RuntimeEvent,RuntimeEventListener}from"./contracts.ts";import{DaniSessionStore,HermesRuntime}from"./hermes-runtime.ts";
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(r=>rmSync(r,{recursive:true,force:true})));
function fake(){const ls=new Set<RuntimeEventListener>();let turn:any;const instance={driverKind:"hermesAgent",adapter:{provider:"hermesAgent",capabilities:{sessionModelSwitch:"unsupported"},onEvent:(l:RuntimeEventListener)=>(ls.add(l),()=>ls.delete(l)),sendTurn:async(i:any)=>(turn=i,{turnId:"t"}),interruptTurn:async()=>{},respondToRequest:async()=>"unavailable" as const,hasSession:()=>false,stopAll:async()=>{}},instanceId:"h",displayName:"Hermes",enabled:true,models:{default:"",options:[]},snapshot:async()=>({state:"available" as const}),dispose:async()=>{}} as ProviderInstance;return{instance,emit:(e:RuntimeEvent)=>ls.forEach(l=>l(e)),turn:()=>turn}}
describe("HermesRuntime",()=>{it("persists native session and resumes it",async()=>{const root=mkdtempSync(join(tmpdir(),"hr-"));roots.push(root);const s=new DaniSessionStore(join(root,"s.db")),f=fake(),r=new HermesRuntime(f.instance,s);const p=r.run({ownerId:"u",botId:"b",threadId:"x",text:"hi"});await new Promise(q=>setTimeout(q,0));f.emit({eventId:"1",provider:"hermesAgent",threadId:"x",createdAt:new Date().toISOString(),type:"session.started",sessionId:"native"});f.emit({eventId:"2",provider:"hermesAgent",threadId:"x",turnId:"t",createdAt:new Date().toISOString(),type:"turn.completed",ok:true});await p;expect(s.get("x")?.nativeCursor).toBe("native");const p2=r.run({ownerId:"u",botId:"b",threadId:"x",text:"again"});await new Promise(q=>setTimeout(q,0));expect(f.turn().resumeCursor).toBe("native");f.emit({eventId:"3",provider:"hermesAgent",threadId:"x",createdAt:new Date().toISOString(),type:"turn.completed",ok:true});await p2;r.dispose();s.close()})});

describe("HermesRuntime recovery and cancellation",()=>{
  it("marks a persisted running session interrupted on restart",()=>{const root=mkdtempSync(join(tmpdir(),"hr-recover-"));roots.push(root);const path=join(root,"s.db");let s=new DaniSessionStore(path);s.save({id:"s",ownerId:"u",botId:"b",provider:"hermes",threadId:"x",nativeCursor:"cursor",state:"running",updatedAt:new Date().toISOString()});s.close();s=new DaniSessionStore(path);const f=fake(),r=new HermesRuntime(f.instance,s);expect(s.get("x")?.state).toBe("interrupted");r.dispose();s.close()});
  it("interrupts and rejects an aborted turn",async()=>{const root=mkdtempSync(join(tmpdir(),"hr-cancel-"));roots.push(root);const s=new DaniSessionStore(join(root,"s.db")),f=fake(),r=new HermesRuntime(f.instance,s),controller=new AbortController();const turn=r.run({ownerId:"u",botId:"b",threadId:"x",text:"hi",signal:controller.signal});await new Promise(q=>setTimeout(q,0));controller.abort(new Error("cancelled"));await expect(turn).rejects.toThrow("cancelled");expect(s.get("x")?.state).toBe("interrupted");r.dispose();s.close()});
});
