import {randomUUID}from"node:crypto";import{mkdirSync}from"node:fs";import{dirname}from"node:path";import{DatabaseSync}from"node:sqlite";import{digestJson}from"./dani-control-plane.ts";
export type MemoryKind="profile"|"project"|"person"|"recap"|"fact";
export interface MemoryWrite{ownerId:string;kind:MemoryKind;key:string;value:unknown;source:{type:string;id:string;observedAt:string};confidence:number}
export class MemorySidecar{private db:DatabaseSync;constructor(path:string){mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS memory_items(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL,kind TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,value_digest TEXT NOT NULL,confidence REAL NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(owner_id,kind,key,value_digest));CREATE TABLE IF NOT EXISTS memory_provenance(id TEXT PRIMARY KEY,item_id TEXT NOT NULL REFERENCES memory_items(id) ON DELETE CASCADE,source_type TEXT NOT NULL,source_id TEXT NOT NULL,observed_at TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(item_id,source_type,source_id));CREATE VIRTUAL TABLE IF NOT EXISTS memory_fts USING fts5(key,value,content='memory_items',content_rowid='rowid',tokenize='unicode61');CREATE TRIGGER IF NOT EXISTS memory_ai AFTER INSERT ON memory_items BEGIN INSERT INTO memory_fts(rowid,key,value)VALUES(new.rowid,new.key,new.value);END;CREATE TRIGGER IF NOT EXISTS memory_ad AFTER DELETE ON memory_items BEGIN INSERT INTO memory_fts(memory_fts,rowid,key,value)VALUES('delete',old.rowid,old.key,old.value);END;CREATE TRIGGER IF NOT EXISTS memory_au AFTER UPDATE ON memory_items BEGIN INSERT INTO memory_fts(memory_fts,rowid,key,value)VALUES('delete',old.rowid,old.key,old.value);INSERT INTO memory_fts(rowid,key,value)VALUES(new.rowid,new.key,new.value);END;`)}close(){this.db.close()}
 write(input:MemoryWrite){const at=new Date().toISOString(),id=randomUUID(),value=JSON.stringify(input.value),digest=digestJson(input.value);this.db.prepare(`INSERT OR IGNORE INTO memory_items VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,input.ownerId,input.kind,input.key,value,digest,input.confidence,"active",at,at);const item=this.db.prepare("SELECT id FROM memory_items WHERE owner_id=? AND kind=? AND key=? AND value_digest=?").get(input.ownerId,input.kind,input.key,digest)as{id:string};this.db.prepare("INSERT OR IGNORE INTO memory_provenance VALUES(?,?,?,?,?,?)").run(randomUUID(),item.id,input.source.type,input.source.id,input.source.observedAt,at);this.reconcile(input.ownerId,input.kind,input.key);return item.id}
 private reconcile(ownerId:string,kind:string,key:string){const rows=this.db.prepare("SELECT id,confidence,updated_at FROM memory_items WHERE owner_id=? AND kind=? AND key=? AND status='active' ORDER BY confidence DESC,updated_at DESC").all(ownerId,kind,key)as{id:string;confidence:number}[];if(rows.length<2)return;const winner=rows[0]!;for(const row of rows.slice(1))if(row.confidence<=winner.confidence)this.db.prepare("UPDATE memory_items SET status='superseded' WHERE id=?").run(row.id)}
 search(ownerId:string,query:string,limit=8){const tokens=query.trim().split(/\s+/).filter(Boolean).map(x=>`"${x.replaceAll('"','')}"`).join(" OR ");if(!tokens)return[];return this.db.prepare(`SELECT m.id,m.kind,m.key,m.value,m.confidence,m.updated_at,bm25(memory_fts) rank FROM memory_fts JOIN memory_items m ON m.rowid=memory_fts.rowid WHERE memory_fts MATCH ? AND m.owner_id=? AND m.status='active' ORDER BY rank,m.confidence DESC LIMIT ?`).all(tokens,ownerId,Math.min(limit,20)).map((r:any)=>({...r,value:JSON.parse(r.value),provenance:this.db.prepare("SELECT source_type,source_id,observed_at FROM memory_provenance WHERE item_id=?").all(r.id)}))}
 context(ownerId:string,query:string,maxChars=4000){const results=this.search(ownerId,query);const out:string[]=[];let used=0;for(const r of results){const line=`[${r.kind}:${r.key}] ${JSON.stringify(r.value)} (sources: ${r.provenance.map((p:any)=>`${p.source_type}:${p.source_id}`).join(", ")})`;if(used+line.length>maxChars)break;out.push(line);used+=line.length}return out.join("\n")}
}
